### PR TITLE
add Uptime.com

### PR DESCRIPTION
**Pull request by MedoAngel**
## Checklist

- [x] The company has at least 50 employees
- [x] The company has multiple open positions that require programming skills
- [x] The company is hiring globally (i.e., not limited by timezone or to rich countries)

### CODE REVIEW

**Comment by yanirs** [comment]
Thanks @MedoAngel. Where did you get the employee count from?

**Comment by MedoAngel** [comment]
From their profile at glassdoor, 

https://www.glassdoor.com/Overview/Working-at-Uptime-EI_IE3008273.11,17.htm

**Comment by yanirs** [comment]
Thanks. LinkedIn said there are fewer employees, but let's go with Glassdoor's estimate. Can you please make the following changes?
- Replace `SaaS for websites` with `Website monitoring tools`
- Replace `HTML, CSS, JS` with `Web`
- Add the Glassdoor link, as for other entries

**Comment by MedoAngel** [comment]
@yanirs I Just added the changes you requested, Can you please check if I need to modify anything?

**Comment by yanirs** [comment]
Ah, sorry, but I just noticed that [this is the correct Glassdoor link for Uptime.com](https://www.glassdoor.com/Overview/Working-at-Uptime-com-EI_IE5057822.11,21.htm). Like LinkedIn, it lists the company as having 1-50 employees, so below the threshold for inclusion.

Closing for now, but thank you for contributing!

**Pull request closed without merging**
