### PR TITLE
Add BeenVerified, LTV

### PR DESCRIPTION
**Pull request by kamoh**
Adding BeenVerified and The Lifetime Value Company.

### CODE REVIEW

**Comment by yanirs** [comment]
Thanks @kamoh, but it looks like both companies lead to BeenVerified, which doesn't seem particularly remote-friendly (even if there are a couple of remote roles).

**Comment by kamoh** [comment]
@yanirs What makes you say that? I work for that company (we undergoing a rebranding of sorts, hence two listings) and I'm one of 20+ full-time remote employees in the US :)

**Comment by yanirs** [comment]
Looking at the career page for BeenVerified, there's no mention of remote. It should at least be noted as an option.

**Comment by kamoh** [comment]
That's a fair point, thanks for pointing that out. I'm talking with HR to improve the messaging there to make it more clear that we do hire remote.

Btw, if you click on the listing for Full-Stack Engineer, it does explicitly say that that role is for a remote/WFH candidate:

image

https://www.beenverified.com/careers/job/job_20190823193802_PEDG2SRFMRUWC7XN/

That said, the location _does_ say `New York, NY`, so that could be cleaned up to avoid confusion. I'll see what I can do!

**Pull request closed without merging**
