### PR TITLE
Added Appwrite

### PR DESCRIPTION
**Pull request by eldadfux**
Added Appwrite to the list. 
https://appwrite.io
https://appwrite.io/company/careers

### CODE REVIEW

**Comment by yanirs** [comment]
Thanks @eldadfux. Based on LinkedIn, it looks like Appwrite doesn't meet the size criterion of this list (at least 50 employees). Is this right or do you have over 50 employees?

**Comment by eldadfux** [comment]
Not 50 yet, but we should get to their pretty soon :)

**Comment by yanirs** [comment]
Alright, can revisit when you get there then. :slightly_smiling_face:

**Comment by eldadfux** [comment]
Just for general knowledge, what the purpose of this limit? I mean, we're hiring too, we're fully remote, fully open-source, got [fresh funding from top VCs](https://appwrite.io/seed), is this the right filter for "established"?

**Comment by yanirs** [comment]
Yeah, it's not a perfect criterion, but it's fairly easy to verify and it helps exclude [hundreds to thousands of similar companies](https://angel.co/remote). Larger companies also tend to have Glassdoor profiles, which help potential candidates assess fit.

**Pull request closed without merging**
