### PR TITLE
Update DataRobot Entry

### PR DESCRIPTION
**Pull request by iveksl2**

### CODE REVIEW

**Comment by yanirs** [comment]
@iveksl2 Thanks, but what does "data science democratization" actually mean? It sounds more like a sales pitch than an actual product description, and is a bit weird when applied to a company that targets enterprise customers...

**Comment by iveksl2** [comment]
@yanirs good point, so what I have in mind specifically is 'democratization' refers to less technical users being able to build and gain insights from a machine learning model without having to program in Python or R. For a traditional datascientist 'Automation' refers to automating all of the mechanical aspects of a data scientist workflow. (Optimal model selection, hyper-parameter optimization, etc.) 

Let me know if you would like me to change the wording. Thanks

**Comment by yanirs** [comment]
@iveksl2 Thanks, but I think that the original "data science as a service" describes it well enough, so I'm closing this PR for now.

**Comment by iveksl2** [comment]
@yanirs no worries, interesting blog, Australia is special to us as its technically the birthplace of kaggle, we may want to "reconnect with our roots" :) and establish a presence, reach out if your interested in making a dent.

**Comment by iveksl2** [comment]
P.S. @yanirs last micro suggestion is you should attach some code or code references on your blogpost on causality modeling so they user can dig in and try some of the techniques themselves. Its on my to-do list :)

**Comment by yanirs** [comment]
Thanks @iveksl2, adding some code is definitely on my ever-expanding to-do list :slightly_smiling_face:

**Pull request closed without merging**
