### PR TITLE
Add XWP to the list.

### PR DESCRIPTION
**Pull request by kopepasah**
XWP is a well established, sister company of X-Team, with a focus different than that of X-Team.

### CODE REVIEW

**Comment by yanirs** [comment]
Thanks @kopepasah. How big is XWP?

**Comment by mehigh** [comment]
Our guild is 50 magicians strong right now :). Looking forward to joining our sister company in the list.

**Comment by kopepasah** [comment]
:point_up: What he said! 😃

**Comment by yanirs** [comment]
Thanks! :slightly_smiling_face:

**Pull request merged**
