### PR TITLE
Add MailerLite

### PR DESCRIPTION
**Pull request by pstoncius**
submitting this request :)

### CODE REVIEW

**Comment by yanirs** [comment]
Thanks @pstoncius!

**Comment by pstoncius** [comment]
Thanks to you @yanirs! 🙌

**Comment by lfilho** [comment]
I think the "competitive salary" cell is not right here.

Looking at a `php and javascript developer`, it says: `Competitive salary: $50,000-$60,000 (gross)`. I don't think 60k pre-tax is competitive, is it?

**Comment by yanirs** [comment]
Good point, @lfilho. I didn't dig into the specific job listings. I'll merge your PR (#122). :slightly_smiling_face:

**Pull request merged**
