### PR TITLE
Add O'Reilly Media

### PR DESCRIPTION
**Pull request by katylava**

### CODE REVIEW

**Comment by augieschwer** [comment]
👍

**Comment by yanirs** [comment]
Thanks @katylava, but it looks like O'Reilly Media doesn't offer proper remote work. There is no mention of it on the [locations page](http://www.oreilly.com/careers/locations.html), and [this job ad](http://www.oreilly.com/careers/?p=job%2FowpP5fwz) says that:
> Our team is located in the United States.  We happily support a variety of employees who are able to come into our offices in Boston, MA or Sebastopol, CA but we cannot offer fulltime employment to others who live and operate outside of the United States.

**Comment by katylava** [comment]
What is "proper remote work"? There are no currently open remote positions but there [have been in the past](https://www.flexjobs.com/jobs/telecommuting-jobs-at-o'reilly_media) and there will be again. A significant portion of our engineering team is remote. Also, [here is a statement by Tim O'Reilly](http://scottberkun.com/2013/how-many-companies-are-100-distributed/comment-page-2/#comment-157869):

> At O’Reilly Media, we have several hundred employees. We have two principal locations in the US (Sebastopol, CA and Cambridge, MA), as well as in the UK, Germany, Japan, and China. Many employees (including me) work remotely even if they are in commuting distance of one of those offices. However, we have employees who work from home in the better part of a dozen states. (Off the top of my head, I can think of CT, NY, MD, WA, RI, CO, NJ in addition to CA and MA.)

If someone is looking for a remote engineering position, I would recommend keeping an eye on our jobs page.

**Comment by yanirs** [comment]
Sounds good to me :slightly_smiling_face:

**Pull request merged**
