### PR TITLE
Add Cloudbeds

### PR DESCRIPTION
**Pull request by DevJackSmith**

### CODE REVIEW

**Comment by yanirs** [comment]
Thanks @DevJackSmith! Can you please add a Glassdoor link and more specific tech?

**Comment by DevJackSmith** [comment]
there are usually many positions open, not just tech ones, but as you can see sales, and management. So the tech differs from PHP, Javascript, HTML, CSS, etc to Infra like AWS, Yaml, Ansible, Python, Shell/Bash, to Zendesk, and others. And it changes too as we find better ways to do what we need we hire people who are experts in that tech.

**Comment by yanirs** [comment]
> there are usually many positions open, not just tech ones

The focus of the list is on tech jobs. That's why the column is titled `Tech stack/skills`.

> So the tech differs from PHP, Javascript, HTML, CSS, etc to Infra like AWS, Yaml, Ansible, Python, Shell/Bash

That can be summarised as `PHP, Web, DevOps` then.

**Comment by yanirs** [comment]
Thanks @DevJackSmith!

**Pull request merged**
