### PR TITLE
Added ToolJet

### PR DESCRIPTION
**Pull request by withshubh**
## Checklist

- [ ] The company has at least 50 employees
- [x] The company has multiple open positions that require programming skills
- [x] The company is hiring globally (i.e., not limited by timezone or to rich countries)

### CODE REVIEW

**Comment by azzamsa** [comment]
The company must comply with the 3 mentioned requirements. Otherwise, it will be rejected.

**Comment by azzamsa** [comment]
@yanirs If you need more hand to manage the PRs in this repo. I am all in.

**Comment by withshubh** [comment]
> The company must comply with the 3 mentioned requirements. Otherwise, it will be rejected.

No problem. Thanks for letting me know! @azzamsa

**Comment by yanirs** [comment]
> @yanirs If you need more hand to manage the PRs in this repo. I am all in.

Thanks @azzamsa, casual help is welcome, but no pressure. :slightly_smiling_face:

**Pull request closed without merging**
