### PR TITLE
add Marco Polo to the list

### PR DESCRIPTION
**Pull request by curtcaldwell**

### CODE REVIEW

**Comment by curtcaldwell** [comment]
Add Marco Polo to list.

**Comment by yanirs** [comment]
Thanks @curtcaldwell, but the Marco Polo website doesn't seem to have much information. Am I missing something?

**Comment by curtcaldwell** [comment]
Hey sorry,

https://www.getjoya.com/ will be better.

I can update it

**Comment by yanirs** [comment]
> https://www.getjoya.com/ will be better.

That website doesn't contain much information either. It looks like Joya/Marco Polo isn't a great fit for the list, so I'm closing this PR.

**Pull request closed without merging**
